### ISSUE TITLE
Fix Hudson failure

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#111]
Hudson failed because of test. For instance see :

https://hudson.eclipse.org/tm4e/job/snapshot/org.eclipse$org.eclipse.tm4e.core.tests/63/testReport/junit/org.eclipse.tm4e.core.grammar.internal/RawTestImpl/org_eclipse_tm4e_core_grammar_internal_RawTestImpl_2f490758/

Here the error:

```
org.eclipse.tm4e.core.grammar.internal.RawTestImpl.org.eclipse.tm4e.core.grammar.internal.RawTestImpl@2f490758 (from org.eclipse.tm4e.core.grammar.GrammarSuiteTest)

En échec depuis 1 build (Depuis Instable#63 )
A duré 15 ms.
Message d'erreur

class "org.eclipse.tm4e.core.grammar.IGrammarRepository"'s signer information does not match signer information of other classes in the same package
Pile d'exécution

java.lang.SecurityException: class "org.eclipse.tm4e.core.grammar.IGrammarRepository"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.tm4e.core.registry.Registry.<init>(Registry.java:57)
	at org.eclipse.tm4e.core.grammar.internal.RawTestImpl.executeTest(RawTestImpl.java:108)
	at org.eclipse.tm4e.core.grammar.internal.RawTestImpl.run(RawTestImpl.java:73)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:99)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:136)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:109)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

I don't understand this error and more travis doesn't fali? https://travis-ci.org/eclipse/tm4e/builds

@mickaelistria @pascalleclercq  when you will have time, please help me, thanks!

**Comment by mickaelistria** [comment]
IIRC, we alraedy faced this issue and the best and simplest solution is to avoid split package: test and bundles should be in different packages otherwise they're both expected to be signed the same way; which is not the case with the Maven setup.

**Comment by mickaelistria** [comment]
The version of dotnet on travis seems to be older than necessary to provide templates: https://travis-ci.org/mickaelistria/aCute/builds/242039955#L1880 . Feel free to add change to the .travis.yml together with the PR if you think it makes sense.

**Comment by angelozerr** [comment]
Thanks @mickaelistria for your explanation. What do you think about https://github.com/eclipse/tm4e/pull/112 ?

**Comment by mickaelistria** [comment]
I think PR #112 is fine, but you shouldn't use split-packages anyway as it often cause issue to JVM, OSGi or p2.

**Comment by angelozerr** [comment]
> split-packages

What do you mean? Could you do a PR please, thanks. Anyway update site works again, thanks @pascalleclercq !

**Comment by mickaelistria** [comment]
Ci build has been working fine for a while.
