### ISSUE TITLE
TM4E breaks default occurrence highlighting in GenericEditor

### ISSUE THREAD

**Issue by creckord** [eclipse/tm4e#151]
GenericEditor recently added a default occurrence highlighter in [bug 521382](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521382). It highlights all occurrences of the current word throughout the document. This stops working as soon as TM4E is installed.

TM4E version: 0.1.0.201709192210
Generic Editor version: org.eclipse.ui.genericeditor 1.1.0.v20171128-0922

**Comment by angelozerr** [comment]
That's strange, I had quicly tested and it worked well?

Have you a demo? Which grammar do you use?

**Comment by creckord** [comment]
I'm using a very simple RCP, which is just the latest org.eclipse.platform.ide from http://download.eclipse.org/eclipse/updates/4.8-I-builds/ with the latest TM4E from http://download.eclipse.org/tm4e/snapshots/

The problem occurs even on files that have no grammar associated with them - in fact it also happens if there isn't any grammar defined in TM4E at all...

Steps:

1. Create a project, and within it a simple highlight.txt file
2. Open the file with the Generic Editor
3. Add some plain-text content to the text file. For example this snippet from the RCP help contents:
> Workbench
> 
> The term Workbench refers to the desktop development environment. The Workbench aims to achieve seamless tool integration and controlled openness by providing a common paradigm for the creation, management, and navigation of workspace resources.
> 
> Each Workbench window contains one or more perspectives.  Perspectives contain views and editors and control what appears in certain menus and tool bars.  More than one Workbench window can exist on the desktop at any given time.
3. Make sure that "Mark occurrences" is activated in the toolbar
4. Select a word that occurs multiple times in the text, e.g. `Workbench` in the example above
5. Expected outcome: all occurrences of `Workbench` are highlighted with a grey background
6. Actual outcome: Nothing happens

I've tracked this down to the `TMPresentationReconciler`. Without TM4E installed, the GenericEditor has a default `org.eclipse.jface.text.presentation.PresentationReconciler`, which applies the word occurrence annotations here:
```java
java.lang.Throwable
	at org.eclipse.jface.text.source.AnnotationPainter.applyTextPresentation(AnnotationPainter.java:993)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4755)
	at org.eclipse.jface.text.presentation.PresentationReconciler.applyTextRegionCollection(PresentationReconciler.java:559)
	at org.eclipse.jface.text.presentation.PresentationReconciler.processDamage(PresentationReconciler.java:548)
	at org.eclipse.jface.text.presentation.PresentationReconciler.access$3(PresentationReconciler.java:544)
	at org.eclipse.jface.text.presentation.PresentationReconciler$InternalListener.textChanged(PresentationReconciler.java:212)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2699)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3344)
	at org.eclipse.jface.text.source.AnnotationPainter.invalidateTextPresentation(AnnotationPainter.java:967)
	at org.eclipse.jface.text.source.AnnotationPainter.updatePainting(AnnotationPainter.java:949)
	at org.eclipse.jface.text.source.AnnotationPainter.access$1(AnnotationPainter.java:943)
	at org.eclipse.jface.text.source.AnnotationPainter$1.run(AnnotationPainter.java:1074)
```

With the `TMPresentationReconciler` installed however, nothing of the sort happens. In fact, `TMPresentationReconciler.enabled` is `false` when I debug into it, and even setting it to true doesn't help, apparently since it's only concerned with TextMate coloring and doesn't seem handle the other stuff that the default `PresentationReconciler` does.
