### ISSUE TITLE
NullPointerException when using custom theme file

### ISSUE THREAD

**Issue by j-ulrich** [eclipse/tm4e#261]
I am trying to use a custom theme (.css) file. But after adding it to the TextMate themes list, I get a NullPointerException whenever the theme is used (e.g. clicking the theme in the list, setting the theme for a grammar, opening a file after the theme has been set etc.):

```
eclipse.buildId=4.17.0.I20200902-1800
java.version=14.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE

org.eclipse.jface
Error
Tue Nov 03 10:22:20 CET 2020
Problems occurred when invoking code from plug-in: "org.eclipse.jface".

java.lang.NullPointerException
	at org.eclipse.tm4e.ui.themes.css.CSSTokenProvider.getEditorBackground(CSSTokenProvider.java:89)
	at org.eclipse.tm4e.ui.themes.Theme.getEditorBackground(Theme.java:97)
	at org.eclipse.tm4e.ui.themes.Theme.initializeViewerColors(Theme.java:160)
	at org.eclipse.tm4e.ui.internal.widgets.TMViewer.setTheme(TMViewer.java:74)
	at org.eclipse.tm4e.ui.internal.preferences.ThemePreferencePage.preview(ThemePreferencePage.java:337)
	at org.eclipse.tm4e.ui.internal.preferences.ThemePreferencePage.lambda$0(ThemePreferencePage.java:189)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2132)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1178)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1207)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:237)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:58)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.runCommand(CocoaUIHandler.java:421)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.access$0(CocoaUIHandler.java:407)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler$1.widgetSelected(CocoaUIHandler.java:281)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

The path and name shown in the theme list in the preferences are correct. However, there is no Plugin ID because it is not a plugin but just a plain .css file.

In case it matters, the CSS file contains an `.editor` block:
```css
/* Editor */
.editor {
	background-color: #FFFFFF;
	color: #000000;
}
```

I'm using Eclipse TM4E 0.4.1.202008270629 (org.eclipse.tm4e.ui).

**Comment by j-ulrich** [comment]
Possibly related to #234

**Comment by mickaelistria** [comment]
Thanks for this report.
I've pushed to master a patch to improve logging (so we should now better know the root cause of such exception). Can you please try upgrading to latest snapshot from https://download.eclipse.org/tm4e/snapshots/ and reproduce the error, and share the log content (it should be a bit richer now).
Thanks in advsnce.

**Comment by j-ulrich** [comment]
Okay. Now I got this exception in addition:
```
org.eclipse.tm4e.ui
Error
Mon Nov 09 14:32:43 CET 2020


java.lang.UnsupportedOperationException
	at org.eclipse.tm4e.core.internal.css.CSSSelectorFactory.createDescendantSelector(CSSSelectorFactory.java:59)
	at org.apache.batik.css.parser.Parser.parseSelector(Parser.java:657)
	at org.apache.batik.css.parser.Parser.parseSelectorList(Parser.java:625)
	at org.apache.batik.css.parser.Parser.parseRuleSet(Parser.java:592)
	at org.apache.batik.css.parser.Parser.parseStyleSheet(Parser.java:233)
	at org.eclipse.tm4e.core.theme.css.CSSParser.<init>(CSSParser.java:61)
	at org.eclipse.tm4e.core.theme.css.CSSParser.<init>(CSSParser.java:49)
	at org.eclipse.tm4e.core.theme.css.CSSParser.<init>(CSSParser.java:39)
	at org.eclipse.tm4e.ui.themes.css.CSSTokenProvider.<init>(CSSTokenProvider.java:40)
	at org.eclipse.tm4e.ui.themes.Theme.getTokenProvider(Theme.java:135)
	at org.eclipse.tm4e.ui.themes.Theme.getEditorBackground(Theme.java:96)
	at org.eclipse.tm4e.ui.themes.Theme.initializeViewerColors(Theme.java:160)
	at org.eclipse.tm4e.ui.internal.widgets.TMViewer.setTheme(TMViewer.java:74)
	at org.eclipse.tm4e.ui.internal.preferences.ThemePreferencePage.preview(ThemePreferencePage.java:337)
	at org.eclipse.tm4e.ui.internal.preferences.ThemePreferencePage.lambda$0(ThemePreferencePage.java:189)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2132)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1662)
	at org.eclipse.jface.viewers.TableViewer.setSelection(TableViewer.java:165)
	at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:376)
	at org.eclipse.tm4e.ui.internal.preferences.ThemePreferencePage$1.handleEvent(ThemePreferencePage.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
[...]
```

I replaced the descendant selectors and now it works.
Thanks!

However, note that the `UnsupportedOperationException` was shown without any message in the exception log:

![image](https://user-images.githubusercontent.com/1260380/98548791-3c7c0200-229a-11eb-964a-03f5910028f3.png)

Maybe you should add a message like "Problems occurred when parsing CSS file" or something.

**Comment by mickaelistria** [comment]
> Maybe you should add a message like "Problems occurred when parsing CSS file" or something.

Can you please submit a PR for that?
