### ISSUE TITLE
Long files can cause freezes

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#275]
See https://github.com/eclipse/wildwebdeveloper/issues/667
When frozen, the UI Freeze monitoring reports the following stack traces:
```
Stack Trace
	at org.eclipse.tm4e.core.internal.css.CSSConditionalSelector.nbMatch(CSSConditionalSelector.java:61)
	at org.eclipse.tm4e.core.theme.css.CSSParser.getBestStyle(CSSParser.java:73)
	at org.eclipse.tm4e.ui.themes.css.CSSTokenProvider.getToken(CSSTokenProvider.java:71)
	at org.eclipse.tm4e.ui.themes.Theme.getToken(Theme.java:83)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.toToken(TMPresentationReconciler.java:614)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:560)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:309)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2709)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3353)
```
or
```
Stack Trace
	at org.eclipse.tm4e.core.internal.css.CSSAndCondition.nbMatch(CSSAndCondition.java:32)
	at org.eclipse.tm4e.core.internal.css.CSSConditionalSelector.nbMatch(CSSConditionalSelector.java:62)
	at org.eclipse.tm4e.core.theme.css.CSSParser.getBestStyle(CSSParser.java:73)
	at org.eclipse.tm4e.ui.themes.css.CSSTokenProvider.getToken(CSSTokenProvider.java:71)
	at org.eclipse.tm4e.ui.themes.Theme.getToken(Theme.java:83)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.toToken(TMPresentationReconciler.java:614)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:560)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:309)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2709)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3353)
```
and others, all mentioning `TMPresentationReconciler.colorize()`

**Comment by sebthom** [comment]
I cannot reproduce this with the latest TM4E release. I can see how the file gets incrementally colorized without the UI freezing.

**Comment by mickaelistria** [comment]
I don't think I got annoyed by this issue for a while, so I'm fine closing this old and probably outdated report.
