### ISSUE TITLE
NullPointerException when using an XtextDocument

### ISSUE THREAD

**Issue by rubenporras** [eclipse/tm4e#277]
When trying out Tm4e with Xtext I get the following exception

java.lang.NullPointerException
	at org.eclipse.tm4e.languageconfiguration.LanguageConfigurationAutoEditStrategy.findContentTypes(LanguageConfigurationAutoEditStrategy.java:188)
	at org.eclipse.tm4e.languageconfiguration.LanguageConfigurationAutoEditStrategy.customizeDocumentCommand(LanguageConfigurationAutoEditStrategy.java:50)
	at org.eclipse.jface.text.TextViewer.customizeDocumentCommand(TextViewer.java:3599)
	at org.eclipse.jface.text.TextViewer.handleVerifyEvent(TextViewer.java:3636)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.handleVerifyEvent(ProjectionViewer.java:1243)
	at org.eclipse.jface.text.TextViewer$TextVerifyListener.verifyText(TextViewer.java:426)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:277)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7378)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8274)
	at org.eclipse.swt.custom.StyledText.doBackspace(StyledText.java:2307)
	at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7199)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6061)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6088)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5786)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1106)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1102)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1489)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4888)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4768)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

The json file configuring Tm4e (https://github.com/rubenporras/dsl-devkit/commit/249d6c5d49e166243ec39cfb84b100b4487d28d1#diff-0fa02eeb4d10e2fbab279021712f563b95b0736be70d5c644019c4d839f05e5a), the plug-in.xml (https://github.com/rubenporras/dsl-devkit/commit/249d6c5d49e166243ec39cfb84b100b4487d28d1#diff-b2b9e847f3138fefaa1252275f8b0503c93fad33fdd5a864b027934ef23bfef9) as well as all the other parts of the code can be seen in GitHub:

https://github.com/rubenporras/dsl-devkit/commit/249d6c5d49e166243ec39cfb84b100b4487d28d1

Could you help me? Is this a bug in the Tm4e code or missconfiguration? I do not think it is related to https://github.com/eclipse/tm4e/issues/242, but if it is an you are waiting for a PatchSet with a null check, I would be willing to do the PR.

Regards

**Comment by mickaelistria** [comment]
Which version of TM4E are you using? Do you know what's the actual NPE here? Eg running with latest Java release gives good NPE message to find out what's wrong. Have you tried debugging it?

**Comment by rubenporras** [comment]
Hi,

I am using TM4E 0.4.2 and tried with Xtext 2.19 and Xtext 2.25 with the same error.

I also debugged it, as far as I see, the document which is created in the editor is an Xtext Document (that is because the ExtensionBasedTextEditor gets an XtextDocumentProvider when opening the file in the editor

Thread [main] (Suspended (breakpoint at line 91 in XtextDocument))	
	XtextDocument.<init>(DocumentTokenSource, ITextEditComposer) line: 91	
	XtextDocument$$FastClassByGuice$$200774039.GUICE$TRAMPOLINE(int, Object, Object[]) line: not available	
	XtextDocument$$FastClassByGuice$$200774039.apply(Object, Object) line: not available	
	DefaultConstructionProxyFactory$FastClassProxy<T>.newInstance(Object...) line: 82	
	ConstructorInjector<T>.provision(InternalContext, ConstructionContext<T>) line: 114	
	ConstructorInjector<T>.construct(InternalContext, Dependency<?>, ProvisionListenerStackCallback<T>) line: 91	
	ConstructorBindingImpl$Factory<T>.get(InternalContext, Dependency<?>, boolean) line: 296	
	InjectorImpl$1.get() line: 1100	
	XtextDocumentProvider.createEmptyDocument() line: 137	
	XtextDocumentProvider.createEmptyDocument() line: 1	
	XtextDocumentProvider(StorageDocumentProvider).createDocument(Object) line: 224	
	XtextDocumentProvider.createDocument(Object) line: 150	
	XtextDocumentProvider(FileDocumentProvider).createElementInfo(Object) line: 686	
	XtextDocumentProvider.createElementInfo(Object) line: 265	
	XtextDocumentProvider(AbstractDocumentProvider).connect(Object) line: 395	
	ExtensionBasedTextEditor(AbstractTextEditor).doSetInput(IEditorInput) line: 4169	
	ExtensionBasedTextEditor(StatusTextEditor).doSetInput(IEditorInput) line: 260	
	ExtensionBasedTextEditor(AbstractDecoratedTextEditor).doSetInput(IEditorInput) line: 1477	
	ExtensionBasedTextEditor(TextEditor).doSetInput(IEditorInput) line: 153	
	ExtensionBasedTextEditor.doSetInput(IEditorInput) line: 71	
	ExtensionBasedTextEditor(AbstractTextEditor).lambda$1(IEditorInput, IProgressMonitor) line: 3136	
	443006437.run(IProgressMonitor) line: not available	
	WorkbenchWindow.run(boolean, boolean, IRunnableWithProgress) line: 2193	
	ExtensionBasedTextEditor(AbstractTextEditor).internalInit(IWorkbenchWindow, IEditorSite, IEditorInput) line: 3153	
	ExtensionBasedTextEditor(AbstractTextEditor).init(IEditorSite, IEditorInput) line: 3178	
	EditorReference.initialize(IWorkbenchPart) line: 365	
	CompatibilityEditor(CompatibilityPart).create() line: 345	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 566	
	MethodRequestor.execute() line: 58	
	InjectorImpl.processAnnotated(Class<Annotation>, Object, Class<?>, PrimaryObjectSupplier, PrimaryObjectSupplier, ArrayList<Class<?>>) line: 1001	
	InjectorImpl.processAnnotated(Class<Annotation>, Object, Class<?>, PrimaryObjectSupplier, PrimaryObjectSupplier, ArrayList<Class<?>>) line: 966	
	InjectorImpl.internalInject(Object, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 139	
	InjectorImpl.internalMake(Class<?>, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 411	
	InjectorImpl.make(Class<T>, PrimaryObjectSupplier) line: 333	
	ContextInjectionFactory.make(Class<T>, IEclipseContext) line: 202	
	ReflectionContributionFactory.createFromBundle(Bundle, IEclipseContext, IEclipseContext, URI) line: 91	
	ReflectionContributionFactory.doCreate(String, IEclipseContext, IEclipseContext) line: 60	
	ReflectionContributionFactory.create(String, IEclipseContext) line: 42	
	ContributedPartRenderer.createWidget(MUIElement, Object) line: 132	
	PartRenderingEngine.createWidget(MUIElement, Object) line: 1015	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 675	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	StackRenderer.showTab(MUIElement) line: 1295	
	StackRenderer(LazyStackRenderer).postProcess(MUIElement) line: 105	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 693	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	AreaRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine$1.run() line: 560	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement, Object, IEclipseContext) line: 544	
	ElementReferenceRenderer.createWidget(MUIElement, Object) line: 73	
	PartRenderingEngine.createWidget(MUIElement, Object) line: 1015	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 675	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	SashRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	SashRenderer.processContents(MElementContainer<MUIElement>) line: 140	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	SashRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	SashRenderer.processContents(MElementContainer<MUIElement>) line: 140	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	SashRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	SashRenderer.processContents(MElementContainer<MUIElement>) line: 140	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	PerspectiveRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	PerspectiveRenderer.processContents(MElementContainer<MUIElement>) line: 51	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	PerspectiveStackRenderer.showTab(MUIElement) line: 82	
	PerspectiveStackRenderer(LazyStackRenderer).postProcess(MUIElement) line: 105	
	PerspectiveStackRenderer.postProcess(MUIElement) line: 64	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 693	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	SashRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	SashRenderer.processContents(MElementContainer<MUIElement>) line: 140	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	WBWRenderer(SWTPartRenderer).processContents(MElementContainer<MUIElement>) line: 72	
	WBWRenderer.processContents(MElementContainer<MUIElement>) line: 665	
	PartRenderingEngine.safeCreateGui(MUIElement, Object, IEclipseContext) line: 689	
	PartRenderingEngine.safeCreateGui(MUIElement) line: 781	
	PartRenderingEngine.access$0(PartRenderingEngine, MUIElement) line: 752	
	PartRenderingEngine$2.run() line: 746	
	SafeRunner.run(ISafeRunnable) line: 45	
	PartRenderingEngine.createGui(MUIElement) line: 730	
	PartRenderingEngine$5.run() line: 1099	
	Realm.runWithDefault(Realm, Runnable) line: 338	
	PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1062	
	E4Workbench.createAndRunUI(MApplicationElement) line: 155	
	Workbench.lambda$3(Display, WorkbenchAdvisor, int[]) line: 644	
	254952533.run() line: not available	
	Realm.runWithDefault(Realm, Runnable) line: 338	
	Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 566	
	PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 150	
	IDEApplication.start(IApplicationContext) line: 155	
	EclipseAppHandle.run(Object) line: 203	
	EclipseAppLauncher.runApplication(Object) line: 137	
	EclipseAppLauncher.start(Object) line: 107	
	EclipseStarter.run(Object) line: 400	
	EclipseStarter.run(String[], Runnable) line: 255	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 566	
	Main.invokeFramework(String[], URL[]) line: 661	
	Main.basicRun(String[]) line: 597	
	Main.run(String[]) line: 1476	
	Main.main(String[]) line: 1449	
	
Then later LSPEclipseUtils.toUri(document) for the XtextDocument returns null (org.eclipse.lsp4e.LSPEclipseUtils.getFile(IDocument) returns null as well).

I do not know why this happen. I am surprissed the generic editor creates an XtextDocument, I would have expected it should create a "generic" document, and not an Xtext Document. Could that be the problem?

Thanks for any help in advance

**Comment by mickaelistria** [comment]
> Then later LSPEclipseUtils.toUri(document) for the XtextDocument returns null (insided it rg.eclipse.lsp4e.LSPEclipseUtils.getFile(IDocument) returns null, FileBuffers.getTextFileBufferManager().getTextFileBuffer(document) returns null as well).

I'm not sure I'm following. Is the issue you see happening in TM4E or LSP4E (or both) ?

> I do not know why this happen. I am surprissed the generic editor creates an XtextDocument, I would have expected it should create a "generic" document, and not an Xtext Document. Could that be the problem?

The editor is usually not responsible for creating the document and delegates this to some dedicated services, and it's possible to plug some specific factories to create specific documents. At the moment, TM4E and LSP4E are not working very well with such custom documents.

**Comment by rubenporras** [comment]
Thanks for your help, I understand that I need to disable the XtextDocumentProvider, I have done that and now the NPE does not appear any longer.

I will close the issue.
