### ISSUE TITLE
Index out of bounds at the end of file

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/tm4e#31]
I'm playing wiht PHP syntax coloring and I noticed `Index out of bounds` exception in some cases. I'm using latest master.

To reproduce:
* create file, its important to have many empty lines at the end (e.g. 4)
```php
<?php

$aaa = new Test();
str(




```
* put cursor at the end of file
* remove all empty lines till '(' (with backspace)

Stacktrace:
java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:9910)
	at org.eclipse.swt.custom.StyledText.replaceStyleRanges(StyledText.java:7911)
	at org.eclipse.jface.text.TextViewer.addPresentation(TextViewer.java:4692)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4769)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.applyTextRegionCollection(TMPresentationReconciler.java:493)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:394)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.access$5(TMPresentationReconciler.java:326)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:191)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2699)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3344)
	at org.eclipse.jface.text.source.AnnotationPainter.invalidateTextPresentation(AnnotationPainter.java:970)
	at org.eclipse.jface.text.source.AnnotationPainter.updatePainting(AnnotationPainter.java:952)
	at org.eclipse.jface.text.source.AnnotationPainter.access$1(AnnotationPainter.java:946)
	at org.eclipse.jface.text.source.AnnotationPainter$1.run(AnnotationPainter.java:1079)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)

**Comment by angelozerr** [comment]
I'm sorry I cannot reproduce your problem. Could you do a demo please. Thanks!

**Comment by mniewrzal** [comment]
Sorry for quality ;)
![demo](https://cloud.githubusercontent.com/assets/7313031/21929533/428018fe-d991-11e6-8a1d-4c777b183af5.gif)

**Comment by angelozerr** [comment]
> Sorry for quality ;)

No, no @mniewrzal, it's not your fault! At first many thank's to create issues to improve TM4E. I know that there are several bugs.

I cannot reproduce your problem because I hae tried with my basic PHP editor which doesn't support validation. Your problem comes from validation which invalidate text presentation. I'm able to reproduce the problem with my TypeScript editor which manage validation too. I will try to fix it and I hope it will fix your problem.

Anyway, thank's to create issues!

**Comment by mniewrzal** [comment]
I found simpler to reproduce case. I'm just opening php file with content (php tag + one empty line):
```php
<?php

```

**Comment by angelozerr** [comment]
I think it's not perfect, but please retry with my commit.

**Comment by mniewrzal** [comment]
Case from my last comment isn't throwing `Index out of bounds` but initial case (from gif demo) is still valid.

**Comment by angelozerr** [comment]
Have you again the problem with https://github.com/angelozerr/textmate.java/commit/6dc3c5ea49a3c93a0ba5082d0bf5478022a3a5d6 ?

**Comment by mniewrzal** [comment]
I tried both described cases with latest master (with your fix) and initial problem is still visible.

**Comment by angelozerr** [comment]
Ok thanks @mniewrzal. Let's me implement https://github.com/angelozerr/textmate.java/issues/33 and you will able to generate a test case. I could see with the generated test what is the problem (I hope).

**Comment by angelozerr** [comment]
@mniewrzal I have started to implement my idea about test generator. See https://github.com/angelozerr/textmate.java/issues/33 but it's not perfect

To activate you must set `TMPresentationReconciler.GENERATE_TEST` to true.

After open your editor, do your change and close your editor. In the console you will see Java code which emulate your scenario.

Please send me your generated Java test + your grammar. Thanks!

**Comment by mniewrzal** [comment]
With latest master I cannot reproduce the issue anymore :)

**Comment by angelozerr** [comment]
@mniewrzal could you remove this line https://github.com/angelozerr/textmate.java/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L387 and tell me if you have a problem?

I must really write a lot of JUnits. Please wait for https://github.com/angelozerr/textmate.java/issues/33 and after it should be very cool if you could push JUNit tests with your PHP editor.

**Comment by mickaelistria** [comment]
Can we mark this issue as fixed according to last comment from @mniewrzal ?

**Comment by angelozerr** [comment]
Yes sure @mickaelistria I think it's an old issue.
