### ISSUE TITLE
TM4E fails to load XML Grammar

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/tm4e#545]
TM4E fails to load the VSCode provided XML  grammar.

While running the WildWebDeveloper JUnit tests (see: https://github.com/eclipse/wildwebdeveloper/pull/1244) using the following configuration:
  - the grammar used -  https://github.com/microsoft/vscode/blob/main/extensions/xml/syntaxes/xml.tmLanguage.json
  - the language configuration used  - https://github.com/microsoft/vscode/blob/main/extensions/xml/xml.language-configuration.json 

the Generic Editor cannot be open with the following error logged:
```
Jun 08, 2023 1:32:02 PM org.eclipse.tm4e.core.registry.Registry _doLoadSingleGrammar
SEVERE: Loading grammar for scope [text.xml] failed: class java.lang.String cannot be cast to class org.eclipse.tm4e.core.internal.types.IRawRule (java.lang.String is in module java.base of loader 'bootstrap'; org.eclipse.tm4e.core.internal.types.IRawRule is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @38093ffe)
```
  
A few related exceptions is logged, while trying to execute JUnit rests using the mentioned grammar:
```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-06-08 13:32:02.829
!MESSAGE No grammar provided for <text.xml>
!STACK 0
org.eclipse.tm4e.core.TMException: No grammar provided for <text.xml>
	at org.eclipse.tm4e.core.internal.grammar.dependencies.ScopeDependencyProcessor.collectReferencesOfReference(ScopeDependencyProcessor.java:117)
	at org.eclipse.tm4e.core.internal.grammar.dependencies.ScopeDependencyProcessor.processQueue(ScopeDependencyProcessor.java:82)
	at org.eclipse.tm4e.core.registry.Registry._loadGrammar(Registry.java:141)
	at org.eclipse.tm4e.core.registry.Registry.loadGrammar(Registry.java:128)
	at org.eclipse.tm4e.registry.internal.AbstractGrammarRegistryManager.getGrammar(AbstractGrammarRegistryManager.java:177)
	at org.eclipse.tm4e.registry.internal.AbstractGrammarRegistryManager.getGrammarForScope(AbstractGrammarRegistryManager.java:127)
	at org.eclipse.tm4e.registry.internal.AbstractGrammarRegistryManager.getGrammarFor(AbstractGrammarRegistryManager.java:115)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.findGrammar(TMPresentationReconciler.java:425)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.findGrammar(TMPresentationReconciler.java:284)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.inputDocumentChanged(TMPresentationReconciler.java:228)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2849)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2890)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:682)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:368)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:632)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3980)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3472)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:454)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor.createPartControl(ExtensionBasedTextEditor.java:166)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	...

!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-06-08 13:32:11.438
!MESSAGE java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 36 column 18 path $.wordPattern
!STACK 0
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 36 column 18 path $.wordPattern
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1075)
	at org.eclipse.tm4e.languageconfiguration.internal.model.LanguageConfiguration.load(LanguageConfiguration.java:205)
	at org.eclipse.tm4e.languageconfiguration.internal.registry.LanguageConfigurationDefinition.getLanguageConfiguration(LanguageConfigurationDefinition.java:138)
	at org.eclipse.tm4e.languageconfiguration.internal.registry.LanguageConfigurationDefinition.getCharacterPair(LanguageConfigurationDefinition.java:89)
	at org.eclipse.tm4e.languageconfiguration.internal.registry.LanguageConfigurationRegistryManager._getCharacterPairSupport(LanguageConfigurationRegistryManager.java:236)
	at org.eclipse.tm4e.languageconfiguration.internal.registry.LanguageConfigurationRegistryManager.shouldSurroundingPairs(LanguageConfigurationRegistryManager.java:103)
	at org.eclipse.tm4e.languageconfiguration.internal.LanguageConfigurationCharacterPairMatcher.getMatcher(LanguageConfigurationCharacterPairMatcher.java:120)
	at org.eclipse.tm4e.languageconfiguration.internal.LanguageConfigurationCharacterPairMatcher.match(LanguageConfigurationCharacterPairMatcher.java:51)
	at org.eclipse.jface.text.source.MatchingCharacterPainter.paint(MatchingCharacterPainter.java:313)
	at org.eclipse.jface.text.PaintManager.addPainter(PaintManager.java:207)
	at org.eclipse.jface.text.TextViewer.addPainter(TextViewer.java:5179)
	at org.eclipse.ui.texteditor.SourceViewerDecorationSupport.showMatchingCharacters(SourceViewerDecorationSupport.java:679)
	at org.eclipse.ui.texteditor.SourceViewerDecorationSupport.updateTextDecorations(SourceViewerDecorationSupport.java:283)
	at org.eclipse.ui.texteditor.SourceViewerDecorationSupport.install(SourceViewerDecorationSupport.java:269)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:456)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor.createPartControl(ExtensionBasedTextEditor.java:166)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	...
```

**Comment by vrubezhny** [comment]
The full stacktrace hidden by the logged error message:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.eclipse.tm4e.core.internal.types.IRawRule (java.lang.String is in module java.base of loader 'bootstrap'; org.eclipse.tm4e.core.internal.types.IRawRule is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @63b58ff4)
	at org.eclipse.tm4e.core.internal.grammar.RawCaptures.setProperty(RawCaptures.java:1)
	at org.eclipse.tm4e.core.internal.parser.PListContentHandler$PListObject.addValue(PListContentHandler.java:100)
	at org.eclipse.tm4e.core.internal.parser.PListContentHandler.endElement(PListContentHandler.java:184)
	at org.eclipse.tm4e.core.internal.parser.PListParserJSON.parse(PListParserJSON.java:72)
	at org.eclipse.tm4e.core.internal.grammar.GrammarReader.readGrammar(GrammarReader.java:52)
	at org.eclipse.tm4e.core.registry.Registry._doLoadSingleGrammar(Registry.java:163)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.eclipse.tm4e.core.registry.Registry._loadSingleGrammar(Registry.java:153)
	at org.eclipse.tm4e.core.registry.Registry.lambda$0(Registry.java:140)
	at java.base/java.util.ArrayDeque.forEach(ArrayDeque.java:888)
	at org.eclipse.tm4e.core.registry.Registry._loadGrammar(Registry.java:140)
	at org.eclipse.tm4e.core.registry.Registry.loadGrammar(Registry.java:128)
	at org.eclipse.tm4e.registry.internal.AbstractGrammarRegistryManager.getGrammar(AbstractGrammarRegistryManager.java:177)
	at org.eclipse.tm4e.registry.internal.AbstractGrammarRegistryManager.getGrammarForScope(AbstractGrammarRegistryManager.java:127)
	at org.eclipse.tm4e.registry.internal.AbstractGrammarRegistryManager.getGrammarFor(AbstractGrammarRegistryManager.java:115)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.findGrammar(TMPresentationReconciler.java:425)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.findGrammar(TMPresentationReconciler.java:284)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.inputDocumentChanged(TMPresentationReconciler.java:228)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2849)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2890)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:682)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:368)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:632)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3980)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3472)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:454)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor.createPartControl(ExtensionBasedTextEditor.java:166)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	...
```

**Comment by sebthom** [comment]
This is a syntax error in the [microsoft/vscode@main/extensions/xml/syntaxes/xml.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/xml/syntaxes/xml.tmLanguage.json?rgh-link-date=2023-06-08T13%3A00%3A02Z) file.

At https://github.com/microsoft/vscode/blob/7ff66b360d5f1cdbdbfa8e10842457e38117713d/extensions/xml/syntaxes/xml.tmLanguage.json#L354-L363

```json
{
  "begin": "<%--",
  "captures": {
     "0": {
        "name": "punctuation.definition.comment.xml"
     },
     "end": "--%>",
     "name": "comment.block.xml"
  }
},
```
needs to be
```json
{
  "begin": "<%--",
  "captures": {
     "0": {
        "name": "punctuation.definition.comment.xml"
     }
   },
   "end": "--%>",
   "name": "comment.block.xml"
},
```

**Comment by sebthom** [comment]
I opened a issue https://github.com/microsoft/vscode/issues/184852 and a PR https://github.com/microsoft/vscode/pull/184853

**Comment by sebthom** [comment]
We apparently also have that issue in the TextMate file in the language pack. I fixed it with https://github.com/eclipse/tm4e/commit/4643498774efe949089cb7b1be353bf86cf99dc2

**Comment by vrubezhny** [comment]
@sebthom Thanks for investigating!
