### ISSUE TITLE
java.lang.IllegalThreadStateException with TMModel.startTokenizerThread

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#578]
I report this error that we have reported me(I have not tested on my side).

On `Mac OS,` with  `eclipse 2023-09 M1` when pom.xml is opened, the editor crash:

![image](https://github.com/eclipse/tm4e/assets/1932211/f12572b0-6aee-4bbc-889c-600f1ebcf0d8)

and there is this stack trace:

```
java.lang.IllegalThreadStateException
	at java.base/java.lang.Thread.start(Thread.java:1567)
	at org.eclipse.tm4e.core.model.TMModel.startTokenizerThread(TMModel.java:249)
	at org.eclipse.tm4e.core.model.TMModel.addModelTokensChangedListener(TMModel.java:223)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:332)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2789)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3409)
	at org.eclipse.jface.text.TextViewer.initializeWidgetContents(TextViewer.java:3457)
	at org.eclipse.jface.text.TextViewer.setVisibleDocument(TextViewer.java:3496)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setVisibleDocument(ProjectionViewer.java:700)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.executeReplaceVisibleDocument(ProjectionViewer.java:755)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.replaceVisibleDocument(ProjectionViewer.java:743)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.reinitializeProjection(ProjectionViewer.java:1221)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.catchupWithProjectionAnnotationModel(ProjectionViewer.java:937)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.processCatchupRequest(ProjectionViewer.java:857)
	at org.eclipse.jface.text.source.projection.ProjectionViewer$AnnotationModelListener.processModelChanged(ProjectionViewer.java:122)
	at org.eclipse.jface.text.source.projection.ProjectionViewer$AnnotationModelListener.modelChanged(ProjectionViewer.java:114)
	at org.eclipse.jface.text.source.AnnotationModel.fireModelChanged(AnnotationModel.java:592)
	at org.eclipse.jface.text.source.AnnotationModel$InternalModelListener.modelChanged(AnnotationModel.java:256)
	at org.eclipse.jface.text.source.AnnotationModel.fireModelChanged(AnnotationModel.java:592)
	at org.eclipse.jface.text.source.AnnotationModel.fireModelChanged(AnnotationModel.java:558)
	at org.eclipse.jface.text.source.projection.ProjectionAnnotationModel.modifyAnnotations(ProjectionAnnotationModel.java:188)
	at org.eclipse.ui.internal.genericeditor.folding.IndentFoldingStrategy.reconcile(IndentFoldingStrategy.java:315)
	at org.eclipse.ui.internal.genericeditor.folding.IndentFoldingStrategy.initialReconcile(IndentFoldingStrategy.java:520)
	at org.eclipse.ui.internal.genericeditor.folding.IndentFoldingStrategy.lambda$0(IndentFoldingStrategy.java:165)
	at org.eclipse.jface.text.source.AnnotationModel.addAnnotationModelListener(AnnotationModel.java:449)
	at org.eclipse.ui.internal.genericeditor.folding.IndentFoldingStrategy.projectionEnabled(IndentFoldingStrategy.java:160)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.fireProjectionEnabled(ProjectionViewer.java:475)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.enableProjection(ProjectionViewer.java:523)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1375)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor$1.doOperation(ExtensionBasedTextEditor.java:118)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor.createPartControl(ExtensionBasedTextEditor.java:179)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:227)
	at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:331)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:203)
	at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:313)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.addFallbackEditors(MavenPomEditor.java:361)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.addPages(MavenPomEditor.java:337)
	at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:143)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:333)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:971)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:936)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:142)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:313)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:105)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5250)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:661)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:625)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:793)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1267)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3233)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:3123)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3121)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3091)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3082)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:548)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:508)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:367)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:172)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:288)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:254)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:274)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:252)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerActionGroup.handleOpen(PackageExplorerActionGroup.java:366)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart$3.open(PackageExplorerPart.java:545)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:800)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:797)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1115)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:296)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
```

@sebthom have you some idea of the problem? It is very annoying because pom editor cannot open the pom.xml file.

Perhaps this error doesn't exist today, but I would like just to report this error with `eclipse 2023-09 M1` .

//cc @fbricon

**Comment by angelozerr** [comment]
Is not this commit https://github.com/eclipse/tm4e/commit/08dfd4ab76cf633b17dbdd4ce740b82ea1501c33 which could causes this issue?

**Comment by sebthom** [comment]
@angelozerr I don't know which version of tm4e is loaded but the line numbers of the stack trace don't match the latest TM4E version.

The thread is started in TMModel at line 435 and not 249 https://github.com/eclipse/tm4e/blob/2cb80832236bcaa8944a3adf0d9313794d6b79c2/org.eclipse.tm4e.core/src/main/java/org/eclipse/tm4e/core/model/TMModel.java#L435

**Comment by angelozerr** [comment]
> @angelozerr I don't know which version of tm4e is loaded but the line numbers of the stack trace don't match the latest TM4E version.

I don't know

> The thread is started in TMModel at line 435 and not 249

Thanks @sebthom for your answer, hope this error will be fixed

**Comment by angelozerr** [comment]
@fbricon could you try to install the TM4E snapshot  https://download.eclipse.org/tm4e/snapshots/. please

**Comment by fbricon** [comment]
Here's the version I see
<img width="932" alt="Screenshot 2023-08-08 at 11 10 04" src="https://github.com/eclipse/tm4e/assets/148698/48f9a611-5814-4fa4-a953-69486511cbe9">

There's nothing to update from the snapshots repo
<img width="1044" alt="Screenshot 2023-08-08 at 11 13 17" src="https://github.com/eclipse/tm4e/assets/148698/6355c482-9e06-45d2-84d3-ba9498c1bb3b">

**Comment by sebthom** [comment]
This plugin has an update. I don't know why the name is displayed differently.

![image](https://github.com/eclipse/tm4e/assets/426959/2b1de5bd-705c-4d04-9fee-e8d6b040ac61)

**Comment by angelozerr** [comment]
Indeed and the version is different, so @fbricon I think you can try it to install TextMate Core.

**Comment by sebthom** [comment]
This is feature update:
![image](https://github.com/eclipse/tm4e/assets/426959/50c8e7b2-4c43-4b82-9aec-89be1095a864)

Once installed you should get these new plugin versions:
![image](https://github.com/eclipse/tm4e/assets/426959/493a40da-d905-4d1f-85a3-7390a210f2b8)

**Comment by fbricon** [comment]
Ok that worked, bug is gone.

I think whoever depends on tm4e (wwd?), depends on the bundles directly, instead of the feature. Not sure if that's why Eclipse failed to detect something to update though.

Now, hopefully, the updated tm4e finds its way to 2023-09 M2

**Comment by sebthom** [comment]
I think you were using TM4E 0.7.1 or lower. The code should already be fixed as of release 0.8.0 https://download.eclipse.org/tm4e/releases/0.8.0/

**Comment by fbricon** [comment]
Your versioning scheme is fun: release 0.8.0 contains feature org.eclipse.tm4e.feature_0.6.0 which references plugin org.eclipse.tm4e.ui_0.7.0

**Comment by sebthom** [comment]
I am also not happy with it...

**Comment by vrubezhny** [comment]
@angelozerr tn4e goes to WWD p2 repository from the latest Eclipse Release Downloads - https://download.eclipse.org/releases/latest/ - at the moment it looks like it is v.0.7.1 ([org.eclipse.tm4e.core v.0.5.4.202305171341). 
We'll peek up v.0.8.0 (or more recent) when the  "latest" will be switched to 2023-09 release updates.
But I think no one restricts a user to manually update to the latest tm4e release

**Comment by minduch** [comment]
#590 got fixed by installing new components from snapshot repo, see comments in issue 590.

**Comment by fbricon** [comment]
looks like the fix was not contributed to 2023-09-M3

**Comment by HannesWell** [comment]
> looks like the fix was not contributed to 2023-09-M3

Does tm4e not contribute to SimRel directly?
I think it is good to contribute new releases immediatly to the `simrel.build` repo (unless it is a freeze-time).

**Comment by akurtakov** [comment]
https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/commit/?id=231f8e9ef3de96f5d426028eda75225c3ff639d1 is tm4e contribution.
