### ISSUE TITLE
NPE with invalidateTextPresentation

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#78]
In the case with:

 * big file
 * editor is plug with code folding, validation, etc which invalidates the text viewer 

We have the following problem:

```
java.lang.NullPointerException
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:366)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.access$5(TMPresentationReconciler.java:346)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:225)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2699)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3344)
	at org.eclipse.jface.text.source.AnnotationPainter.invalidateTextPresentation(AnnotationPainter.java:970)
	at org.eclipse.jface.text.source.AnnotationPainter.updatePainting(AnnotationPainter.java:952)
	at org.eclipse.jface.text.source.AnnotationPainter.access$1(AnnotationPainter.java:946)
	at org.eclipse.jface.text.source.AnnotationPainter$1.run(AnnotationPainter.java:1079)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

@mickaelistria I think it's a very important issue, tell me if you need more info.

**Comment by mickaelistria** [comment]
What do you think would be better here:
* Add a null-check, or
* make the ModelLine.tokens be an empty list by default, until overridden to another value?

**Comment by mickaelistria** [comment]
Also, was the issue present before the refactoring I made on the thread?

**Comment by angelozerr** [comment]
> What do you think would be better here:

>  * Add a null-check, or make the ModelLine.tokens be an empty list by default, until overridden to another value?

No, I have left this NPE in order to avoid forgetting this issue.

> Also, was the issue present before the refactoring I made on the thread?

Yes, its not your fault.

Let's me try to explain the problem. Takes a sample with TypeScript. Imagine your editor content is like this:

```
let a = "";
a. // here there is an error

```

The coloration is done with `colorize` method https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L346 which is called with 2 means:

 * case 1: on background when TextMate tokens are ready https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L262
 * case 2: when TextViewer#invalidateTextPresentation is called (because of validation, folding, etc) https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L225

When I started tm4e I managed just the case 1. It worked well because my editor was simply and invalidateTextPresentation  was never called. But when I integrate it inside my TypeScriptEditor which called TextViewer#invalidateTextPresentation when folding, validation update annotations, I had this problem:

 * the editor is opened, case 1 colorize the editor (works great)
 * when editor has error, TextViewer#invalidateTextPresentation invalidates some part of the editor and my editor was not colorized.

In other words, I had to manage case 2, to recolorize the editor. It works great when TextMate tokens are ready but throws NPE exception when model line are not ready.

To reproduce the problem, you can install typescript.java, use a big file like tsserver.js (just renam eit to tsserver.ts) and open it. You will see that the first time the editor is colorized and when validation is done, some part of the editor are invalidated and some part of the editor are not colorized because of NPE.

To fix with clean mean this issue, we should improve the case 2:

 * adjust the  `toLineNumber` with the model lines size if `toLineNumber` > model lines size and store somewhere the initial `toLineNumber` 
 * use perhaps CompletableFuture to colorize the part of lines which are not colorized (from= the adujusted `toLineNumber` and to= initial `toLineNumber`)

It's a little hard to explain the problem, tell me if you need more information.

**Comment by angelozerr** [comment]
@mickaelistria I have tried to fix this issue with https://github.com/eclipse/tm4e/commit/ed3eb8c480e8f8f6412e6b3596d62749cce65455 

It works great now with my TypeScript editor (with large file which have validation errors). Please tell me if it works for you. Hope it will not break something.

I'm waiting for your feedback to close this issue. Thanks!

**Comment by mickaelistria** [comment]
I doesn't seem to break any of the use-cases I have (but I never was affected by the issue so far), so feel free to close it. I'll create new issues if necessary.

**Comment by angelozerr** [comment]
> but I never was affected by the issue so fa

Have you validation in your editor which invalidates viewer?

> so feel free to close it. I'll create new issues if necessary.

Ok thanks.
