### ISSUE TITLE
Make TM4E core lib accessible via Maven

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#83]
Since `org.eclipse.tm4e.core` is Eclipse-independent and can be used in plain Java context, it would be great to publish it to Nexus: https://bugs.eclipse.org/bugs/show_bug.cgi?id=514346

**Comment by exoego** [comment]
Hello, publishing to Maven is still planned or abandoned?
If abandoned, I will fork and publish for my usage.

**Comment by mickaelistria** [comment]
If you can contribute to make it happen, it would be very welcome!

**Comment by mickaelistria** [comment]
If you `mvn install` from source code locally, can you then consume the `org.eclipse.tm4e.core` artifact as expected?

**Comment by exoego** [comment]
Well, I could import it as 

```xml
<dependency>
  <groupId>org.eclipse</groupId>
  <artifactId>org.eclipse.tm4e.core</artifactId>
  <vesion>0.3.4-SNAPSHOT</version>
</dependency>
```
(actually I uses `sbt` instead of `mvn`, so `"org.eclipse" % "org.eclipse.tm4e.core" % "0.3.4-SNAPSHOT"` is an actual identifier I used`)

and then Java code 
```java
import org.eclipse.tm4e.core.registry.Registry;
```

is compilable.

The `groupId` and `artifactId` is a bit weird for me, but it works !!

**Comment by exoego** [comment]
Ah, it seems that TM4E does not support JDK 11...
I got this error.

```
[error] java.nio.file.NoSuchFileException: /usr/lib/jvm/lib/tools.jar
[error]         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[error]         at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[error]         at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
[error]         at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[error]         at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
[error]         at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
[error]         at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[error]         at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
[error]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
[error]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
```

Since OpenJDK8 is no longer LTS, I think TM4E should support JDK11.

**Comment by mickaelistria** [comment]
> So... how can I contribute to make this issue forward ?

Here is a suggestion:
You work on having it published on a local instance of Nexus of yours, you submit PRs for necessary change, if any. Once it's working for you, you share your configuration and we work on adapting it to Eclipse Nexus instance (at repository.eclipse.org).

> Ah, it seems that TM4E does not support JDK 11... ???

It does work with JDK 11, at least as an Eclipse IDE plugin.

> I got this error when running a code using org.eclipse.tm4e.core.registry.Registry.

I don't see anywhere in the stack anything related to TM4E. Can you please share a full stack highlighting what operation of tm4e triggers that?

**Comment by exoego** [comment]
Ah, sorry, it was my mistake on build configuration.
Actually it worked on JDK 11.
I will try to publish to my private Nexus.

**Comment by ainslec** [comment]
Hello,

I'm also looking for this on Maven central.

I found this, but it's quite old, and I'd rather work from "org.eclipse" group id.

```
	<dependency>
	  <groupId>org.netbeans.external</groupId>
	  <artifactId>org.eclipse.tm4e.core_0.2.0.201809031154</artifactId>
	  <version>RELEASE110</version>
	</dependency>
```

**Comment by mickaelistria** [comment]
To be honest, I don't think publishing to plain Maven is a functionality I'm going to work on soon as it's not a priority to me. However, we'll totally welcome contributions that go into that direction.
